/*
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.project.browserautomationdsl.ui.internal.BrowserautomationdslActivator;

public class DomainmodelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BrowserautomationdslActivator.getInstance().getInjector("org.xtext.project.browserautomationdsl.Domainmodel");
	}

}
