/*
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainmodelScopeProvider extends DelegatingScopeProvider {
}
