/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.validation;

import org.xtext.project.browserautomationdsl.validation.AbstractDomainmodelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DomainmodelValidator extends AbstractDomainmodelValidator {
}
