/*
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.project.browserautomationdsl.ui.internal.BrowserautomationdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainmodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(BrowserautomationdslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		BrowserautomationdslActivator activator = BrowserautomationdslActivator.getInstance();
		return activator != null ? activator.getInjector(BrowserautomationdslActivator.ORG_XTEXT_PROJECT_BROWSERAUTOMATIONDSL_DOMAINMODEL) : null;
	}

}
