/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>INSTRUCTION</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project.browserautomationdsl.domainmodel.DomainmodelPackage#getINSTRUCTION()
 * @model
 * @generated
 */
public interface INSTRUCTION extends EObject
{
} // INSTRUCTION
