/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>READ</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project.browserautomationdsl.domainmodel.DomainmodelPackage#getREAD()
 * @model
 * @generated
 */
public interface READ extends INSTRUCTION
{
} // READ
