/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.domainmodel.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.project.browserautomationdsl.domainmodel.CHECK;
import org.xtext.project.browserautomationdsl.domainmodel.DomainmodelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>CHECK</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CHECKImpl extends INSTRUCTIONImpl implements CHECK
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CHECKImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainmodelPackage.Literals.CHECK;
  }

} //CHECKImpl
