/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.domainmodel.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.project.browserautomationdsl.domainmodel.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DomainmodelFactoryImpl extends EFactoryImpl implements DomainmodelFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static DomainmodelFactory init()
  {
    try
    {
      DomainmodelFactory theDomainmodelFactory = (DomainmodelFactory)EPackage.Registry.INSTANCE.getEFactory(DomainmodelPackage.eNS_URI);
      if (theDomainmodelFactory != null)
      {
        return theDomainmodelFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new DomainmodelFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DomainmodelFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case DomainmodelPackage.PROGRAMME: return createPROGRAMME();
      case DomainmodelPackage.PROCEDURE: return createPROCEDURE();
      case DomainmodelPackage.INSTRUCTION: return createINSTRUCTION();
      case DomainmodelPackage.OPEN: return createOPEN();
      case DomainmodelPackage.GOTO: return createGOTO();
      case DomainmodelPackage.CLICK: return createCLICK();
      case DomainmodelPackage.FILL: return createFILL();
      case DomainmodelPackage.CHECK: return createCHECK();
      case DomainmodelPackage.UNCHECK: return createUNCHECK();
      case DomainmodelPackage.SELECT: return createSELECT();
      case DomainmodelPackage.READ: return createREAD();
      case DomainmodelPackage.VERIFY: return createVERIFY();
      case DomainmodelPackage.COUNT: return createCOUNT();
      case DomainmodelPackage.SAVEVAR: return createSAVEVAR();
      case DomainmodelPackage.PLAY: return createPLAY();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PROGRAMME createPROGRAMME()
  {
    PROGRAMMEImpl programme = new PROGRAMMEImpl();
    return programme;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PROCEDURE createPROCEDURE()
  {
    PROCEDUREImpl procedure = new PROCEDUREImpl();
    return procedure;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public INSTRUCTION createINSTRUCTION()
  {
    INSTRUCTIONImpl instruction = new INSTRUCTIONImpl();
    return instruction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OPEN createOPEN()
  {
    OPENImpl open = new OPENImpl();
    return open;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GOTO createGOTO()
  {
    GOTOImpl goto_ = new GOTOImpl();
    return goto_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CLICK createCLICK()
  {
    CLICKImpl click = new CLICKImpl();
    return click;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FILL createFILL()
  {
    FILLImpl fill = new FILLImpl();
    return fill;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CHECK createCHECK()
  {
    CHECKImpl check = new CHECKImpl();
    return check;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UNCHECK createUNCHECK()
  {
    UNCHECKImpl uncheck = new UNCHECKImpl();
    return uncheck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SELECT createSELECT()
  {
    SELECTImpl select = new SELECTImpl();
    return select;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public READ createREAD()
  {
    READImpl read = new READImpl();
    return read;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VERIFY createVERIFY()
  {
    VERIFYImpl verify = new VERIFYImpl();
    return verify;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public COUNT createCOUNT()
  {
    COUNTImpl count = new COUNTImpl();
    return count;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SAVEVAR createSAVEVAR()
  {
    SAVEVARImpl savevar = new SAVEVARImpl();
    return savevar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PLAY createPLAY()
  {
    PLAYImpl play = new PLAYImpl();
    return play;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DomainmodelPackage getDomainmodelPackage()
  {
    return (DomainmodelPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static DomainmodelPackage getPackage()
  {
    return DomainmodelPackage.eINSTANCE;
  }

} //DomainmodelFactoryImpl
