/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.domainmodel.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.project.browserautomationdsl.domainmodel.DomainmodelPackage;
import org.xtext.project.browserautomationdsl.domainmodel.UNCHECK;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>UNCHECK</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UNCHECKImpl extends INSTRUCTIONImpl implements UNCHECK
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UNCHECKImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainmodelPackage.Literals.UNCHECK;
  }

} //UNCHECKImpl
