/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.ide;

import org.xtext.project.browserautomationdsl.ide.AbstractDomainmodelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
