/*
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DomainmodelGrammarAccess extends AbstractGrammarElementFinder {
	
	public class PROGRAMMEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.PROGRAMME");
		private final Assignment cProceduresAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cProceduresPROCEDUREParserRuleCall_0 = (RuleCall)cProceduresAssignment.eContents().get(0);
		
		//PROGRAMME:
		//	procedures+=PROCEDURE*;
		@Override public ParserRule getRule() { return rule; }
		
		//procedures+=PROCEDURE*
		public Assignment getProceduresAssignment() { return cProceduresAssignment; }
		
		//PROCEDURE
		public RuleCall getProceduresPROCEDUREParserRuleCall_0() { return cProceduresPROCEDUREParserRuleCall_0; }
	}
	public class PROCEDUREElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.PROCEDURE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcedureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameVARTYPETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cWithKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cParamAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cParamVARTYPETerminalRuleCall_2_1_0 = (RuleCall)cParamAssignment_2_1.eContents().get(0);
		private final Assignment cParamsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cParamsVARTYPETerminalRuleCall_2_2_0 = (RuleCall)cParamsAssignment_2_2.eContents().get(0);
		private final Assignment cInstAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInstINSTRUCTIONParserRuleCall_3_0 = (RuleCall)cInstAssignment_3.eContents().get(0);
		
		//PROCEDURE:
		//	'procedure' name=VARTYPE ('with' param=VARTYPE params+=VARTYPE*)?
		//	inst+=INSTRUCTION*;
		@Override public ParserRule getRule() { return rule; }
		
		//'procedure' name=VARTYPE ('with' param=VARTYPE params+=VARTYPE*)? inst+=INSTRUCTION*
		public Group getGroup() { return cGroup; }
		
		//'procedure'
		public Keyword getProcedureKeyword_0() { return cProcedureKeyword_0; }
		
		//name=VARTYPE
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//VARTYPE
		public RuleCall getNameVARTYPETerminalRuleCall_1_0() { return cNameVARTYPETerminalRuleCall_1_0; }
		
		//('with' param=VARTYPE params+=VARTYPE*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'with'
		public Keyword getWithKeyword_2_0() { return cWithKeyword_2_0; }
		
		//param=VARTYPE
		public Assignment getParamAssignment_2_1() { return cParamAssignment_2_1; }
		
		//VARTYPE
		public RuleCall getParamVARTYPETerminalRuleCall_2_1_0() { return cParamVARTYPETerminalRuleCall_2_1_0; }
		
		//params+=VARTYPE*
		public Assignment getParamsAssignment_2_2() { return cParamsAssignment_2_2; }
		
		//VARTYPE
		public RuleCall getParamsVARTYPETerminalRuleCall_2_2_0() { return cParamsVARTYPETerminalRuleCall_2_2_0; }
		
		//inst+=INSTRUCTION*
		public Assignment getInstAssignment_3() { return cInstAssignment_3; }
		
		//INSTRUCTION
		public RuleCall getInstINSTRUCTIONParserRuleCall_3_0() { return cInstINSTRUCTIONParserRuleCall_3_0; }
	}
	public class INSTRUCTIONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.INSTRUCTION");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOPENParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCLICKParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCHECKParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cUNCHECKParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cREADParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cCOUNTParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cVERIFYParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cSELECTParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cGOTOParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cFILLParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cPLAYParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		
		//INSTRUCTION:
		//	OPEN
		//	| CLICK
		//	| CHECK
		//	| UNCHECK
		//	| READ
		//	| COUNT
		//	| VERIFY
		//	| SELECT
		//	| GOTO
		//	| FILL
		//	| PLAY;
		@Override public ParserRule getRule() { return rule; }
		
		//OPEN | CLICK | CHECK | UNCHECK | READ | COUNT | VERIFY | SELECT | GOTO | FILL | PLAY
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OPEN
		public RuleCall getOPENParserRuleCall_0() { return cOPENParserRuleCall_0; }
		
		//CLICK
		public RuleCall getCLICKParserRuleCall_1() { return cCLICKParserRuleCall_1; }
		
		//CHECK
		public RuleCall getCHECKParserRuleCall_2() { return cCHECKParserRuleCall_2; }
		
		//UNCHECK
		public RuleCall getUNCHECKParserRuleCall_3() { return cUNCHECKParserRuleCall_3; }
		
		//READ
		public RuleCall getREADParserRuleCall_4() { return cREADParserRuleCall_4; }
		
		//COUNT
		public RuleCall getCOUNTParserRuleCall_5() { return cCOUNTParserRuleCall_5; }
		
		//VERIFY
		public RuleCall getVERIFYParserRuleCall_6() { return cVERIFYParserRuleCall_6; }
		
		//SELECT
		public RuleCall getSELECTParserRuleCall_7() { return cSELECTParserRuleCall_7; }
		
		//GOTO
		public RuleCall getGOTOParserRuleCall_8() { return cGOTOParserRuleCall_8; }
		
		//FILL
		public RuleCall getFILLParserRuleCall_9() { return cFILLParserRuleCall_9; }
		
		//PLAY
		public RuleCall getPLAYParserRuleCall_10() { return cPLAYParserRuleCall_10; }
	}
	public class OPENElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.OPEN");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameOpenKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cValueAlternatives_1_0 = (Alternatives)cValueAssignment_1.eContents().get(0);
		private final Keyword cValueFIREFOXKeyword_1_0_0 = (Keyword)cValueAlternatives_1_0.eContents().get(0);
		private final Keyword cValueCHROMEKeyword_1_0_1 = (Keyword)cValueAlternatives_1_0.eContents().get(1);
		
		//OPEN:
		//	name='open' value=('FIREFOX' | 'CHROME');
		@Override public ParserRule getRule() { return rule; }
		
		//name='open' value=('FIREFOX' | 'CHROME')
		public Group getGroup() { return cGroup; }
		
		//name='open'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'open'
		public Keyword getNameOpenKeyword_0_0() { return cNameOpenKeyword_0_0; }
		
		//value=('FIREFOX' | 'CHROME')
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//('FIREFOX' | 'CHROME')
		public Alternatives getValueAlternatives_1_0() { return cValueAlternatives_1_0; }
		
		//'FIREFOX'
		public Keyword getValueFIREFOXKeyword_1_0_0() { return cValueFIREFOXKeyword_1_0_0; }
		
		//'CHROME'
		public Keyword getValueCHROMEKeyword_1_0_1() { return cValueCHROMEKeyword_1_0_1; }
	}
	public class GOTOElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.GOTO");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameGoToKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cGivenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//GOTO:
		//	name='go to' 'given'? value=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name='go to' 'given'? value=STRING
		public Group getGroup() { return cGroup; }
		
		//name='go to'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'go to'
		public Keyword getNameGoToKeyword_0_0() { return cNameGoToKeyword_0_0; }
		
		//'given'?
		public Keyword getGivenKeyword_1() { return cGivenKeyword_1; }
		
		//value=STRING
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_0() { return cValueSTRINGTerminalRuleCall_2_0; }
	}
	public class CLICKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.CLICK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameClickKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cOnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cTypeAlternatives_2_0 = (Alternatives)cTypeAssignment_2.eContents().get(0);
		private final Keyword cTypeBUTTONKeyword_2_0_0 = (Keyword)cTypeAlternatives_2_0.eContents().get(0);
		private final Keyword cTypeLINKKeyword_2_0_1 = (Keyword)cTypeAlternatives_2_0.eContents().get(1);
		private final Keyword cTypeIMAGEKeyword_2_0_2 = (Keyword)cTypeAlternatives_2_0.eContents().get(2);
		private final Keyword cTypeTEXTKeyword_2_0_3 = (Keyword)cTypeAlternatives_2_0.eContents().get(3);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueELEMENTIDENTIFIERParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//CLICK:
		//	name='click' 'on' type=('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') value=ELEMENTIDENTIFIER;
		@Override public ParserRule getRule() { return rule; }
		
		//name='click' 'on' type=('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') value=ELEMENTIDENTIFIER
		public Group getGroup() { return cGroup; }
		
		//name='click'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'click'
		public Keyword getNameClickKeyword_0_0() { return cNameClickKeyword_0_0; }
		
		//'on'
		public Keyword getOnKeyword_1() { return cOnKeyword_1; }
		
		//type=('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT')
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT')
		public Alternatives getTypeAlternatives_2_0() { return cTypeAlternatives_2_0; }
		
		//'BUTTON'
		public Keyword getTypeBUTTONKeyword_2_0_0() { return cTypeBUTTONKeyword_2_0_0; }
		
		//'LINK'
		public Keyword getTypeLINKKeyword_2_0_1() { return cTypeLINKKeyword_2_0_1; }
		
		//'IMAGE'
		public Keyword getTypeIMAGEKeyword_2_0_2() { return cTypeIMAGEKeyword_2_0_2; }
		
		//'TEXT'
		public Keyword getTypeTEXTKeyword_2_0_3() { return cTypeTEXTKeyword_2_0_3; }
		
		//value=ELEMENTIDENTIFIER
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getValueELEMENTIDENTIFIERParserRuleCall_3_0() { return cValueELEMENTIDENTIFIERParserRuleCall_3_0; }
	}
	public class FILLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.FILL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameFillKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cTEXTFIELDKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cSEARCHFIELDKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final RuleCall cELEMENTIDENTIFIERParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cWithKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cAlternatives_4.eContents().get(0);
		private final Keyword cSavedKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cVarAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cVarVARTYPETerminalRuleCall_4_0_1_0 = (RuleCall)cVarAssignment_4_0_1.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cAlternatives_4.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		
		//FILL:
		//	name='fill' ('TEXTFIELD' | 'SEARCHFIELD') ELEMENTIDENTIFIER? 'with' ('saved' var=VARTYPE | value=STRING);
		@Override public ParserRule getRule() { return rule; }
		
		//name='fill' ('TEXTFIELD' | 'SEARCHFIELD') ELEMENTIDENTIFIER? 'with' ('saved' var=VARTYPE | value=STRING)
		public Group getGroup() { return cGroup; }
		
		//name='fill'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'fill'
		public Keyword getNameFillKeyword_0_0() { return cNameFillKeyword_0_0; }
		
		//'TEXTFIELD' | 'SEARCHFIELD'
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'TEXTFIELD'
		public Keyword getTEXTFIELDKeyword_1_0() { return cTEXTFIELDKeyword_1_0; }
		
		//'SEARCHFIELD'
		public Keyword getSEARCHFIELDKeyword_1_1() { return cSEARCHFIELDKeyword_1_1; }
		
		//ELEMENTIDENTIFIER?
		public RuleCall getELEMENTIDENTIFIERParserRuleCall_2() { return cELEMENTIDENTIFIERParserRuleCall_2; }
		
		//'with'
		public Keyword getWithKeyword_3() { return cWithKeyword_3; }
		
		//'saved' var=VARTYPE | value=STRING
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//'saved' var=VARTYPE
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//'saved'
		public Keyword getSavedKeyword_4_0_0() { return cSavedKeyword_4_0_0; }
		
		//var=VARTYPE
		public Assignment getVarAssignment_4_0_1() { return cVarAssignment_4_0_1; }
		
		//VARTYPE
		public RuleCall getVarVARTYPETerminalRuleCall_4_0_1_0() { return cVarVARTYPETerminalRuleCall_4_0_1_0; }
		
		//value=STRING
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_4_1_0() { return cValueSTRINGTerminalRuleCall_4_1_0; }
	}
	public class CHECKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.CHECK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameCheckKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cAllKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCHECKBOXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cELEMENTIDENTIFIERParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//CHECK:
		//	name='check' 'all'? 'CHECKBOX' ELEMENTIDENTIFIER?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='check' 'all'? 'CHECKBOX' ELEMENTIDENTIFIER?
		public Group getGroup() { return cGroup; }
		
		//name='check'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'check'
		public Keyword getNameCheckKeyword_0_0() { return cNameCheckKeyword_0_0; }
		
		//'all'?
		public Keyword getAllKeyword_1() { return cAllKeyword_1; }
		
		//'CHECKBOX'
		public Keyword getCHECKBOXKeyword_2() { return cCHECKBOXKeyword_2; }
		
		//ELEMENTIDENTIFIER?
		public RuleCall getELEMENTIDENTIFIERParserRuleCall_3() { return cELEMENTIDENTIFIERParserRuleCall_3; }
	}
	public class UNCHECKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.UNCHECK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameUncheckKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cAllKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCHECKBOXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cELEMENTIDENTIFIERParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//UNCHECK:
		//	name='uncheck' 'all'? 'CHECKBOX' ELEMENTIDENTIFIER?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='uncheck' 'all'? 'CHECKBOX' ELEMENTIDENTIFIER?
		public Group getGroup() { return cGroup; }
		
		//name='uncheck'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'uncheck'
		public Keyword getNameUncheckKeyword_0_0() { return cNameUncheckKeyword_0_0; }
		
		//'all'?
		public Keyword getAllKeyword_1() { return cAllKeyword_1; }
		
		//'CHECKBOX'
		public Keyword getCHECKBOXKeyword_2() { return cCHECKBOXKeyword_2; }
		
		//ELEMENTIDENTIFIER?
		public RuleCall getELEMENTIDENTIFIERParserRuleCall_3() { return cELEMENTIDENTIFIERParserRuleCall_3; }
	}
	public class SELECTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.SELECT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameSelectKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Assignment cElemAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElemSTRINGTerminalRuleCall_1_0 = (RuleCall)cElemAssignment_1.eContents().get(0);
		private final Keyword cInKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCOMBOBOXKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cELEMENTIDENTIFIERParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//SELECT:
		//	name='select' elem=STRING 'in' 'COMBOBOX' ELEMENTIDENTIFIER?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='select' elem=STRING 'in' 'COMBOBOX' ELEMENTIDENTIFIER?
		public Group getGroup() { return cGroup; }
		
		//name='select'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'select'
		public Keyword getNameSelectKeyword_0_0() { return cNameSelectKeyword_0_0; }
		
		//elem=STRING
		public Assignment getElemAssignment_1() { return cElemAssignment_1; }
		
		//STRING
		public RuleCall getElemSTRINGTerminalRuleCall_1_0() { return cElemSTRINGTerminalRuleCall_1_0; }
		
		//'in'
		public Keyword getInKeyword_2() { return cInKeyword_2; }
		
		//'COMBOBOX'
		public Keyword getCOMBOBOXKeyword_3() { return cCOMBOBOXKeyword_3; }
		
		//ELEMENTIDENTIFIER?
		public RuleCall getELEMENTIDENTIFIERParserRuleCall_4() { return cELEMENTIDENTIFIERParserRuleCall_4; }
	}
	public class READElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.READ");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameReadKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cUrlKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cBUTTONKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Keyword cLINKKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		private final Keyword cIMAGEKeyword_3_2 = (Keyword)cAlternatives_3.eContents().get(2);
		private final Keyword cTEXTKeyword_3_3 = (Keyword)cAlternatives_3.eContents().get(3);
		private final RuleCall cELEMENTIDENTIFIERParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cSAVEVARParserRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//READ:
		//	name='read' 'url' 'from' ('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') ELEMENTIDENTIFIER SAVEVAR?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='read' 'url' 'from' ('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') ELEMENTIDENTIFIER SAVEVAR?
		public Group getGroup() { return cGroup; }
		
		//name='read'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'read'
		public Keyword getNameReadKeyword_0_0() { return cNameReadKeyword_0_0; }
		
		//'url'
		public Keyword getUrlKeyword_1() { return cUrlKeyword_1; }
		
		//'from'
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }
		
		//'BUTTON' | 'LINK' | 'IMAGE' | 'TEXT'
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'BUTTON'
		public Keyword getBUTTONKeyword_3_0() { return cBUTTONKeyword_3_0; }
		
		//'LINK'
		public Keyword getLINKKeyword_3_1() { return cLINKKeyword_3_1; }
		
		//'IMAGE'
		public Keyword getIMAGEKeyword_3_2() { return cIMAGEKeyword_3_2; }
		
		//'TEXT'
		public Keyword getTEXTKeyword_3_3() { return cTEXTKeyword_3_3; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getELEMENTIDENTIFIERParserRuleCall_4() { return cELEMENTIDENTIFIERParserRuleCall_4; }
		
		//SAVEVAR?
		public RuleCall getSAVEVARParserRuleCall_5() { return cSAVEVARParserRuleCall_5; }
	}
	public class ELEMENTIDENTIFIERElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.ELEMENTIDENTIFIER");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIdentifiedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cByKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Keyword cLABELKeyword_2_0 = (Keyword)cAlternatives_2.eContents().get(0);
		private final Keyword cCLASSKeyword_2_1 = (Keyword)cAlternatives_2.eContents().get(1);
		private final Keyword cIDKeyword_2_2 = (Keyword)cAlternatives_2.eContents().get(2);
		private final Keyword cALTKeyword_2_3 = (Keyword)cAlternatives_2.eContents().get(3);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final RuleCall cSTRINGTerminalRuleCall_3_0 = (RuleCall)cAlternatives_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cGivenKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final RuleCall cVARTYPETerminalRuleCall_3_1_1 = (RuleCall)cGroup_3_1.eContents().get(1);
		
		//ELEMENTIDENTIFIER:
		//	'identified' 'by' ('LABEL' | 'CLASS' | 'ID' | 'ALT') (STRING | 'given' VARTYPE);
		@Override public ParserRule getRule() { return rule; }
		
		//'identified' 'by' ('LABEL' | 'CLASS' | 'ID' | 'ALT') (STRING | 'given' VARTYPE)
		public Group getGroup() { return cGroup; }
		
		//'identified'
		public Keyword getIdentifiedKeyword_0() { return cIdentifiedKeyword_0; }
		
		//'by'
		public Keyword getByKeyword_1() { return cByKeyword_1; }
		
		//'LABEL' | 'CLASS' | 'ID' | 'ALT'
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//'LABEL'
		public Keyword getLABELKeyword_2_0() { return cLABELKeyword_2_0; }
		
		//'CLASS'
		public Keyword getCLASSKeyword_2_1() { return cCLASSKeyword_2_1; }
		
		//'ID'
		public Keyword getIDKeyword_2_2() { return cIDKeyword_2_2; }
		
		//'ALT'
		public Keyword getALTKeyword_2_3() { return cALTKeyword_2_3; }
		
		//STRING | 'given' VARTYPE
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_3_0() { return cSTRINGTerminalRuleCall_3_0; }
		
		//'given' VARTYPE
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'given'
		public Keyword getGivenKeyword_3_1_0() { return cGivenKeyword_3_1_0; }
		
		//VARTYPE
		public RuleCall getVARTYPETerminalRuleCall_3_1_1() { return cVARTYPETerminalRuleCall_3_1_1; }
	}
	public class VERIFYElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.VERIFY");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameVerifyKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cThatKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cCountAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cCountCOUNTParserRuleCall_2_0_0 = (RuleCall)cCountAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Alternatives cAlternatives_2_1_0 = (Alternatives)cGroup_2_1.eContents().get(0);
		private final Keyword cPAGEKeyword_2_1_0_0 = (Keyword)cAlternatives_2_1_0.eContents().get(0);
		private final Keyword cTEXTKeyword_2_1_0_1 = (Keyword)cAlternatives_2_1_0.eContents().get(1);
		private final RuleCall cELEMENTIDENTIFIERParserRuleCall_2_1_1 = (RuleCall)cGroup_2_1.eContents().get(1);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cContainsKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Alternatives cAlternatives_3_0_1 = (Alternatives)cGroup_3_0.eContents().get(1);
		private final Group cGroup_3_0_1_0 = (Group)cAlternatives_3_0_1.eContents().get(0);
		private final Alternatives cAlternatives_3_0_1_0_0 = (Alternatives)cGroup_3_0_1_0.eContents().get(0);
		private final Keyword cLINKKeyword_3_0_1_0_0_0 = (Keyword)cAlternatives_3_0_1_0_0.eContents().get(0);
		private final Keyword cIMAGEKeyword_3_0_1_0_0_1 = (Keyword)cAlternatives_3_0_1_0_0.eContents().get(1);
		private final RuleCall cELEMENTIDENTIFIERParserRuleCall_3_0_1_0_1 = (RuleCall)cGroup_3_0_1_0.eContents().get(1);
		private final Assignment cValueAssignment_3_0_1_1 = (Assignment)cAlternatives_3_0_1.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_3_0_1_1_0 = (RuleCall)cValueAssignment_3_0_1_1.eContents().get(0);
		private final Group cGroup_3_0_1_2 = (Group)cAlternatives_3_0_1.eContents().get(2);
		private final Keyword cSavedKeyword_3_0_1_2_0 = (Keyword)cGroup_3_0_1_2.eContents().get(0);
		private final Assignment cVarAssignment_3_0_1_2_1 = (Assignment)cGroup_3_0_1_2.eContents().get(1);
		private final RuleCall cVarVARTYPETerminalRuleCall_3_0_1_2_1_0 = (RuleCall)cVarAssignment_3_0_1_2_1.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cEqualsKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Alternatives cAlternatives_3_1_1 = (Alternatives)cGroup_3_1.eContents().get(1);
		private final Group cGroup_3_1_1_0 = (Group)cAlternatives_3_1_1.eContents().get(0);
		private final Keyword cSavedKeyword_3_1_1_0_0 = (Keyword)cGroup_3_1_1_0.eContents().get(0);
		private final Assignment cVarAssignment_3_1_1_0_1 = (Assignment)cGroup_3_1_1_0.eContents().get(1);
		private final RuleCall cVarVARTYPETerminalRuleCall_3_1_1_0_1_0 = (RuleCall)cVarAssignment_3_1_1_0_1.eContents().get(0);
		private final Assignment cValueAssignment_3_1_1_1 = (Assignment)cAlternatives_3_1_1.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_3_1_1_1_0 = (RuleCall)cValueAssignment_3_1_1_1.eContents().get(0);
		
		//VERIFY:
		//	name='verify' 'that' (count=COUNT | ('PAGE' | 'TEXT') ELEMENTIDENTIFIER?) ('contains' (('LINK' | 'IMAGE')
		//	ELEMENTIDENTIFIER | value=STRING | 'saved' var=VARTYPE) | 'equals' ('saved' var=VARTYPE | value=STRING));
		@Override public ParserRule getRule() { return rule; }
		
		//name='verify' 'that' (count=COUNT | ('PAGE' | 'TEXT') ELEMENTIDENTIFIER?) ('contains' (('LINK' | 'IMAGE')
		//ELEMENTIDENTIFIER | value=STRING | 'saved' var=VARTYPE) | 'equals' ('saved' var=VARTYPE | value=STRING))
		public Group getGroup() { return cGroup; }
		
		//name='verify'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'verify'
		public Keyword getNameVerifyKeyword_0_0() { return cNameVerifyKeyword_0_0; }
		
		//'that'
		public Keyword getThatKeyword_1() { return cThatKeyword_1; }
		
		//count=COUNT | ('PAGE' | 'TEXT') ELEMENTIDENTIFIER?
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//count=COUNT
		public Assignment getCountAssignment_2_0() { return cCountAssignment_2_0; }
		
		//COUNT
		public RuleCall getCountCOUNTParserRuleCall_2_0_0() { return cCountCOUNTParserRuleCall_2_0_0; }
		
		//('PAGE' | 'TEXT') ELEMENTIDENTIFIER?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'PAGE' | 'TEXT'
		public Alternatives getAlternatives_2_1_0() { return cAlternatives_2_1_0; }
		
		//'PAGE'
		public Keyword getPAGEKeyword_2_1_0_0() { return cPAGEKeyword_2_1_0_0; }
		
		//'TEXT'
		public Keyword getTEXTKeyword_2_1_0_1() { return cTEXTKeyword_2_1_0_1; }
		
		//ELEMENTIDENTIFIER?
		public RuleCall getELEMENTIDENTIFIERParserRuleCall_2_1_1() { return cELEMENTIDENTIFIERParserRuleCall_2_1_1; }
		
		//'contains' (('LINK' | 'IMAGE') ELEMENTIDENTIFIER | value=STRING | 'saved' var=VARTYPE) | 'equals' ('saved' var=VARTYPE |
		//value=STRING)
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'contains' (('LINK' | 'IMAGE') ELEMENTIDENTIFIER | value=STRING | 'saved' var=VARTYPE)
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'contains'
		public Keyword getContainsKeyword_3_0_0() { return cContainsKeyword_3_0_0; }
		
		//('LINK' | 'IMAGE') ELEMENTIDENTIFIER | value=STRING | 'saved' var=VARTYPE
		public Alternatives getAlternatives_3_0_1() { return cAlternatives_3_0_1; }
		
		//('LINK' | 'IMAGE') ELEMENTIDENTIFIER
		public Group getGroup_3_0_1_0() { return cGroup_3_0_1_0; }
		
		//'LINK' | 'IMAGE'
		public Alternatives getAlternatives_3_0_1_0_0() { return cAlternatives_3_0_1_0_0; }
		
		//'LINK'
		public Keyword getLINKKeyword_3_0_1_0_0_0() { return cLINKKeyword_3_0_1_0_0_0; }
		
		//'IMAGE'
		public Keyword getIMAGEKeyword_3_0_1_0_0_1() { return cIMAGEKeyword_3_0_1_0_0_1; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getELEMENTIDENTIFIERParserRuleCall_3_0_1_0_1() { return cELEMENTIDENTIFIERParserRuleCall_3_0_1_0_1; }
		
		//value=STRING
		public Assignment getValueAssignment_3_0_1_1() { return cValueAssignment_3_0_1_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_3_0_1_1_0() { return cValueSTRINGTerminalRuleCall_3_0_1_1_0; }
		
		//'saved' var=VARTYPE
		public Group getGroup_3_0_1_2() { return cGroup_3_0_1_2; }
		
		//'saved'
		public Keyword getSavedKeyword_3_0_1_2_0() { return cSavedKeyword_3_0_1_2_0; }
		
		//var=VARTYPE
		public Assignment getVarAssignment_3_0_1_2_1() { return cVarAssignment_3_0_1_2_1; }
		
		//VARTYPE
		public RuleCall getVarVARTYPETerminalRuleCall_3_0_1_2_1_0() { return cVarVARTYPETerminalRuleCall_3_0_1_2_1_0; }
		
		//'equals' ('saved' var=VARTYPE | value=STRING)
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'equals'
		public Keyword getEqualsKeyword_3_1_0() { return cEqualsKeyword_3_1_0; }
		
		//'saved' var=VARTYPE | value=STRING
		public Alternatives getAlternatives_3_1_1() { return cAlternatives_3_1_1; }
		
		//'saved' var=VARTYPE
		public Group getGroup_3_1_1_0() { return cGroup_3_1_1_0; }
		
		//'saved'
		public Keyword getSavedKeyword_3_1_1_0_0() { return cSavedKeyword_3_1_1_0_0; }
		
		//var=VARTYPE
		public Assignment getVarAssignment_3_1_1_0_1() { return cVarAssignment_3_1_1_0_1; }
		
		//VARTYPE
		public RuleCall getVarVARTYPETerminalRuleCall_3_1_1_0_1_0() { return cVarVARTYPETerminalRuleCall_3_1_1_0_1_0; }
		
		//value=STRING
		public Assignment getValueAssignment_3_1_1_1() { return cValueAssignment_3_1_1_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_3_1_1_1_0() { return cValueSTRINGTerminalRuleCall_3_1_1_1_0; }
	}
	public class COUNTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.COUNT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameCountKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cELEMENTKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cELEMENTIDENTIFIERParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cSAVEVARParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//COUNT:
		//	name='count' 'ELEMENT' ELEMENTIDENTIFIER SAVEVAR?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='count' 'ELEMENT' ELEMENTIDENTIFIER SAVEVAR?
		public Group getGroup() { return cGroup; }
		
		//name='count'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'count'
		public Keyword getNameCountKeyword_0_0() { return cNameCountKeyword_0_0; }
		
		//'ELEMENT'
		public Keyword getELEMENTKeyword_1() { return cELEMENTKeyword_1; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getELEMENTIDENTIFIERParserRuleCall_2() { return cELEMENTIDENTIFIERParserRuleCall_2; }
		
		//SAVEVAR?
		public RuleCall getSAVEVARParserRuleCall_3() { return cSAVEVARParserRuleCall_3; }
	}
	public class SAVEVARElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.SAVEVAR");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAndKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cSaveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cInKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cVarAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVarVARTYPETerminalRuleCall_3_0 = (RuleCall)cVarAssignment_3.eContents().get(0);
		
		//SAVEVAR:
		//	'and' 'save' 'in' var=VARTYPE;
		@Override public ParserRule getRule() { return rule; }
		
		//'and' 'save' 'in' var=VARTYPE
		public Group getGroup() { return cGroup; }
		
		//'and'
		public Keyword getAndKeyword_0() { return cAndKeyword_0; }
		
		//'save'
		public Keyword getSaveKeyword_1() { return cSaveKeyword_1; }
		
		//'in'
		public Keyword getInKeyword_2() { return cInKeyword_2; }
		
		//var=VARTYPE
		public Assignment getVarAssignment_3() { return cVarAssignment_3; }
		
		//VARTYPE
		public RuleCall getVarVARTYPETerminalRuleCall_3_0() { return cVarVARTYPETerminalRuleCall_3_0; }
	}
	public class PLAYElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.PLAY");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNamePlayKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cProcedureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cVARTYPETerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cParamsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParamsSTRINGTerminalRuleCall_3_0 = (RuleCall)cParamsAssignment_3.eContents().get(0);
		
		//PLAY:
		//	name='play' 'procedure' VARTYPE params+=STRING*;
		@Override public ParserRule getRule() { return rule; }
		
		//name='play' 'procedure' VARTYPE params+=STRING*
		public Group getGroup() { return cGroup; }
		
		//name='play'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'play'
		public Keyword getNamePlayKeyword_0_0() { return cNamePlayKeyword_0_0; }
		
		//'procedure'
		public Keyword getProcedureKeyword_1() { return cProcedureKeyword_1; }
		
		//VARTYPE
		public RuleCall getVARTYPETerminalRuleCall_2() { return cVARTYPETerminalRuleCall_2; }
		
		//params+=STRING*
		public Assignment getParamsAssignment_3() { return cParamsAssignment_3; }
		
		//STRING
		public RuleCall getParamsSTRINGTerminalRuleCall_3_0() { return cParamsSTRINGTerminalRuleCall_3_0; }
	}
	
	
	private final PROGRAMMEElements pPROGRAMME;
	private final PROCEDUREElements pPROCEDURE;
	private final INSTRUCTIONElements pINSTRUCTION;
	private final OPENElements pOPEN;
	private final GOTOElements pGOTO;
	private final CLICKElements pCLICK;
	private final FILLElements pFILL;
	private final CHECKElements pCHECK;
	private final UNCHECKElements pUNCHECK;
	private final SELECTElements pSELECT;
	private final READElements pREAD;
	private final ELEMENTIDENTIFIERElements pELEMENTIDENTIFIER;
	private final VERIFYElements pVERIFY;
	private final COUNTElements pCOUNT;
	private final SAVEVARElements pSAVEVAR;
	private final PLAYElements pPLAY;
	private final TerminalRule tVARTYPE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DomainmodelGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPROGRAMME = new PROGRAMMEElements();
		this.pPROCEDURE = new PROCEDUREElements();
		this.pINSTRUCTION = new INSTRUCTIONElements();
		this.pOPEN = new OPENElements();
		this.pGOTO = new GOTOElements();
		this.pCLICK = new CLICKElements();
		this.pFILL = new FILLElements();
		this.pCHECK = new CHECKElements();
		this.pUNCHECK = new UNCHECKElements();
		this.pSELECT = new SELECTElements();
		this.pREAD = new READElements();
		this.pELEMENTIDENTIFIER = new ELEMENTIDENTIFIERElements();
		this.pVERIFY = new VERIFYElements();
		this.pCOUNT = new COUNTElements();
		this.pSAVEVAR = new SAVEVARElements();
		this.pPLAY = new PLAYElements();
		this.tVARTYPE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.VARTYPE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.project.browserautomationdsl.Domainmodel".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//PROGRAMME:
	//	procedures+=PROCEDURE*;
	public PROGRAMMEElements getPROGRAMMEAccess() {
		return pPROGRAMME;
	}
	
	public ParserRule getPROGRAMMERule() {
		return getPROGRAMMEAccess().getRule();
	}
	
	//PROCEDURE:
	//	'procedure' name=VARTYPE ('with' param=VARTYPE params+=VARTYPE*)?
	//	inst+=INSTRUCTION*;
	public PROCEDUREElements getPROCEDUREAccess() {
		return pPROCEDURE;
	}
	
	public ParserRule getPROCEDURERule() {
		return getPROCEDUREAccess().getRule();
	}
	
	//INSTRUCTION:
	//	OPEN
	//	| CLICK
	//	| CHECK
	//	| UNCHECK
	//	| READ
	//	| COUNT
	//	| VERIFY
	//	| SELECT
	//	| GOTO
	//	| FILL
	//	| PLAY;
	public INSTRUCTIONElements getINSTRUCTIONAccess() {
		return pINSTRUCTION;
	}
	
	public ParserRule getINSTRUCTIONRule() {
		return getINSTRUCTIONAccess().getRule();
	}
	
	//OPEN:
	//	name='open' value=('FIREFOX' | 'CHROME');
	public OPENElements getOPENAccess() {
		return pOPEN;
	}
	
	public ParserRule getOPENRule() {
		return getOPENAccess().getRule();
	}
	
	//GOTO:
	//	name='go to' 'given'? value=STRING;
	public GOTOElements getGOTOAccess() {
		return pGOTO;
	}
	
	public ParserRule getGOTORule() {
		return getGOTOAccess().getRule();
	}
	
	//CLICK:
	//	name='click' 'on' type=('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') value=ELEMENTIDENTIFIER;
	public CLICKElements getCLICKAccess() {
		return pCLICK;
	}
	
	public ParserRule getCLICKRule() {
		return getCLICKAccess().getRule();
	}
	
	//FILL:
	//	name='fill' ('TEXTFIELD' | 'SEARCHFIELD') ELEMENTIDENTIFIER? 'with' ('saved' var=VARTYPE | value=STRING);
	public FILLElements getFILLAccess() {
		return pFILL;
	}
	
	public ParserRule getFILLRule() {
		return getFILLAccess().getRule();
	}
	
	//CHECK:
	//	name='check' 'all'? 'CHECKBOX' ELEMENTIDENTIFIER?;
	public CHECKElements getCHECKAccess() {
		return pCHECK;
	}
	
	public ParserRule getCHECKRule() {
		return getCHECKAccess().getRule();
	}
	
	//UNCHECK:
	//	name='uncheck' 'all'? 'CHECKBOX' ELEMENTIDENTIFIER?;
	public UNCHECKElements getUNCHECKAccess() {
		return pUNCHECK;
	}
	
	public ParserRule getUNCHECKRule() {
		return getUNCHECKAccess().getRule();
	}
	
	//SELECT:
	//	name='select' elem=STRING 'in' 'COMBOBOX' ELEMENTIDENTIFIER?;
	public SELECTElements getSELECTAccess() {
		return pSELECT;
	}
	
	public ParserRule getSELECTRule() {
		return getSELECTAccess().getRule();
	}
	
	//READ:
	//	name='read' 'url' 'from' ('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') ELEMENTIDENTIFIER SAVEVAR?;
	public READElements getREADAccess() {
		return pREAD;
	}
	
	public ParserRule getREADRule() {
		return getREADAccess().getRule();
	}
	
	//ELEMENTIDENTIFIER:
	//	'identified' 'by' ('LABEL' | 'CLASS' | 'ID' | 'ALT') (STRING | 'given' VARTYPE);
	public ELEMENTIDENTIFIERElements getELEMENTIDENTIFIERAccess() {
		return pELEMENTIDENTIFIER;
	}
	
	public ParserRule getELEMENTIDENTIFIERRule() {
		return getELEMENTIDENTIFIERAccess().getRule();
	}
	
	//VERIFY:
	//	name='verify' 'that' (count=COUNT | ('PAGE' | 'TEXT') ELEMENTIDENTIFIER?) ('contains' (('LINK' | 'IMAGE')
	//	ELEMENTIDENTIFIER | value=STRING | 'saved' var=VARTYPE) | 'equals' ('saved' var=VARTYPE | value=STRING));
	public VERIFYElements getVERIFYAccess() {
		return pVERIFY;
	}
	
	public ParserRule getVERIFYRule() {
		return getVERIFYAccess().getRule();
	}
	
	//COUNT:
	//	name='count' 'ELEMENT' ELEMENTIDENTIFIER SAVEVAR?;
	public COUNTElements getCOUNTAccess() {
		return pCOUNT;
	}
	
	public ParserRule getCOUNTRule() {
		return getCOUNTAccess().getRule();
	}
	
	//SAVEVAR:
	//	'and' 'save' 'in' var=VARTYPE;
	public SAVEVARElements getSAVEVARAccess() {
		return pSAVEVAR;
	}
	
	public ParserRule getSAVEVARRule() {
		return getSAVEVARAccess().getRule();
	}
	
	//PLAY:
	//	name='play' 'procedure' VARTYPE params+=STRING*;
	public PLAYElements getPLAYAccess() {
		return pPLAY;
	}
	
	public ParserRule getPLAYRule() {
		return getPLAYAccess().getRule();
	}
	
	//terminal VARTYPE:
	//	'A'..'Z' | 'a'..'z' | INT | '_' | '-'*;
	public TerminalRule getVARTYPERule() {
		return tVARTYPE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
