/*
 * generated by Xtext 2.15.0
 */
package org.xtext.project.browserautomationdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DomainmodelGrammarAccess extends AbstractGrammarElementFinder {
	
	public class PROGRAMMEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.PROGRAMME");
		private final Assignment cProceduresAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cProceduresPROCEDUREParserRuleCall_0 = (RuleCall)cProceduresAssignment.eContents().get(0);
		
		//PROGRAMME:
		//	procedures+=PROCEDURE*;
		@Override public ParserRule getRule() { return rule; }
		
		//procedures+=PROCEDURE*
		public Assignment getProceduresAssignment() { return cProceduresAssignment; }
		
		//PROCEDURE
		public RuleCall getProceduresPROCEDUREParserRuleCall_0() { return cProceduresPROCEDUREParserRuleCall_0; }
	}
	public class PROCEDUREElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.PROCEDURE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcedureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameVARTYPETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cWithKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cParamAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cParamVARTYPETerminalRuleCall_2_1_0 = (RuleCall)cParamAssignment_2_1.eContents().get(0);
		private final Assignment cParamsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cParamsVARTYPETerminalRuleCall_2_2_0 = (RuleCall)cParamsAssignment_2_2.eContents().get(0);
		private final Assignment cInstAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInstINSTRUCTIONParserRuleCall_3_0 = (RuleCall)cInstAssignment_3.eContents().get(0);
		
		//PROCEDURE:
		//	'procedure' name=VARTYPE ('with' param=VARTYPE params+=VARTYPE*)?
		//	inst+=INSTRUCTION*;
		@Override public ParserRule getRule() { return rule; }
		
		//'procedure' name=VARTYPE ('with' param=VARTYPE params+=VARTYPE*)? inst+=INSTRUCTION*
		public Group getGroup() { return cGroup; }
		
		//'procedure'
		public Keyword getProcedureKeyword_0() { return cProcedureKeyword_0; }
		
		//name=VARTYPE
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//VARTYPE
		public RuleCall getNameVARTYPETerminalRuleCall_1_0() { return cNameVARTYPETerminalRuleCall_1_0; }
		
		//('with' param=VARTYPE params+=VARTYPE*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'with'
		public Keyword getWithKeyword_2_0() { return cWithKeyword_2_0; }
		
		//param=VARTYPE
		public Assignment getParamAssignment_2_1() { return cParamAssignment_2_1; }
		
		//VARTYPE
		public RuleCall getParamVARTYPETerminalRuleCall_2_1_0() { return cParamVARTYPETerminalRuleCall_2_1_0; }
		
		//params+=VARTYPE*
		public Assignment getParamsAssignment_2_2() { return cParamsAssignment_2_2; }
		
		//VARTYPE
		public RuleCall getParamsVARTYPETerminalRuleCall_2_2_0() { return cParamsVARTYPETerminalRuleCall_2_2_0; }
		
		//inst+=INSTRUCTION*
		public Assignment getInstAssignment_3() { return cInstAssignment_3; }
		
		//INSTRUCTION
		public RuleCall getInstINSTRUCTIONParserRuleCall_3_0() { return cInstINSTRUCTIONParserRuleCall_3_0; }
	}
	public class INSTRUCTIONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.INSTRUCTION");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOPENParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCLICKParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCHECKParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cUNCHECKParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cREADParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cCOUNTParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cVERIFYParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cSELECTParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cGOTOParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cFILLParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cPLAYParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		
		//INSTRUCTION:
		//	OPEN
		//	| CLICK
		//	| CHECK
		//	| UNCHECK
		//	| READ
		//	| COUNT
		//	| VERIFY
		//	| SELECT
		//	| GOTO
		//	| FILL
		//	| PLAY;
		@Override public ParserRule getRule() { return rule; }
		
		//OPEN | CLICK | CHECK | UNCHECK | READ | COUNT | VERIFY | SELECT | GOTO | FILL | PLAY
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OPEN
		public RuleCall getOPENParserRuleCall_0() { return cOPENParserRuleCall_0; }
		
		//CLICK
		public RuleCall getCLICKParserRuleCall_1() { return cCLICKParserRuleCall_1; }
		
		//CHECK
		public RuleCall getCHECKParserRuleCall_2() { return cCHECKParserRuleCall_2; }
		
		//UNCHECK
		public RuleCall getUNCHECKParserRuleCall_3() { return cUNCHECKParserRuleCall_3; }
		
		//READ
		public RuleCall getREADParserRuleCall_4() { return cREADParserRuleCall_4; }
		
		//COUNT
		public RuleCall getCOUNTParserRuleCall_5() { return cCOUNTParserRuleCall_5; }
		
		//VERIFY
		public RuleCall getVERIFYParserRuleCall_6() { return cVERIFYParserRuleCall_6; }
		
		//SELECT
		public RuleCall getSELECTParserRuleCall_7() { return cSELECTParserRuleCall_7; }
		
		//GOTO
		public RuleCall getGOTOParserRuleCall_8() { return cGOTOParserRuleCall_8; }
		
		//FILL
		public RuleCall getFILLParserRuleCall_9() { return cFILLParserRuleCall_9; }
		
		//PLAY
		public RuleCall getPLAYParserRuleCall_10() { return cPLAYParserRuleCall_10; }
	}
	public class OPENElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.OPEN");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameOpenKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cValueAlternatives_1_0 = (Alternatives)cValueAssignment_1.eContents().get(0);
		private final Keyword cValueFIREFOXKeyword_1_0_0 = (Keyword)cValueAlternatives_1_0.eContents().get(0);
		private final Keyword cValueCHROMEKeyword_1_0_1 = (Keyword)cValueAlternatives_1_0.eContents().get(1);
		
		//OPEN:
		//	name='open' value=('FIREFOX' | 'CHROME');
		@Override public ParserRule getRule() { return rule; }
		
		//name='open' value=('FIREFOX' | 'CHROME')
		public Group getGroup() { return cGroup; }
		
		//name='open'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'open'
		public Keyword getNameOpenKeyword_0_0() { return cNameOpenKeyword_0_0; }
		
		//value=('FIREFOX' | 'CHROME')
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//('FIREFOX' | 'CHROME')
		public Alternatives getValueAlternatives_1_0() { return cValueAlternatives_1_0; }
		
		//'FIREFOX'
		public Keyword getValueFIREFOXKeyword_1_0_0() { return cValueFIREFOXKeyword_1_0_0; }
		
		//'CHROME'
		public Keyword getValueCHROMEKeyword_1_0_1() { return cValueCHROMEKeyword_1_0_1; }
	}
	public class GOTOElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.GOTO");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameGoToKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cGivenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//GOTO:
		//	name='go to' 'given'? value=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name='go to' 'given'? value=STRING
		public Group getGroup() { return cGroup; }
		
		//name='go to'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'go to'
		public Keyword getNameGoToKeyword_0_0() { return cNameGoToKeyword_0_0; }
		
		//'given'?
		public Keyword getGivenKeyword_1() { return cGivenKeyword_1; }
		
		//value=STRING
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_0() { return cValueSTRINGTerminalRuleCall_2_0; }
	}
	public class CLICKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.CLICK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameClickKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cOnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cTypeAlternatives_2_0 = (Alternatives)cTypeAssignment_2.eContents().get(0);
		private final Keyword cTypeBUTTONKeyword_2_0_0 = (Keyword)cTypeAlternatives_2_0.eContents().get(0);
		private final Keyword cTypeLINKKeyword_2_0_1 = (Keyword)cTypeAlternatives_2_0.eContents().get(1);
		private final Keyword cTypeIMAGEKeyword_2_0_2 = (Keyword)cTypeAlternatives_2_0.eContents().get(2);
		private final Keyword cTypeTEXTKeyword_2_0_3 = (Keyword)cTypeAlternatives_2_0.eContents().get(3);
		private final Assignment cIdentifierAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIdentifierELEMENTIDENTIFIERParserRuleCall_3_0 = (RuleCall)cIdentifierAssignment_3.eContents().get(0);
		
		//CLICK:
		//	name='click' 'on' type=('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER;
		@Override public ParserRule getRule() { return rule; }
		
		//name='click' 'on' type=('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER
		public Group getGroup() { return cGroup; }
		
		//name='click'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'click'
		public Keyword getNameClickKeyword_0_0() { return cNameClickKeyword_0_0; }
		
		//'on'
		public Keyword getOnKeyword_1() { return cOnKeyword_1; }
		
		//type=('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT')
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT')
		public Alternatives getTypeAlternatives_2_0() { return cTypeAlternatives_2_0; }
		
		//'BUTTON'
		public Keyword getTypeBUTTONKeyword_2_0_0() { return cTypeBUTTONKeyword_2_0_0; }
		
		//'LINK'
		public Keyword getTypeLINKKeyword_2_0_1() { return cTypeLINKKeyword_2_0_1; }
		
		//'IMAGE'
		public Keyword getTypeIMAGEKeyword_2_0_2() { return cTypeIMAGEKeyword_2_0_2; }
		
		//'TEXT'
		public Keyword getTypeTEXTKeyword_2_0_3() { return cTypeTEXTKeyword_2_0_3; }
		
		//identifier=ELEMENTIDENTIFIER
		public Assignment getIdentifierAssignment_3() { return cIdentifierAssignment_3; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getIdentifierELEMENTIDENTIFIERParserRuleCall_3_0() { return cIdentifierELEMENTIDENTIFIERParserRuleCall_3_0; }
	}
	public class FILLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.FILL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameFillKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Assignment cFieldTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cFieldTypeAlternatives_1_0 = (Alternatives)cFieldTypeAssignment_1.eContents().get(0);
		private final Keyword cFieldTypeTEXTFIELDKeyword_1_0_0 = (Keyword)cFieldTypeAlternatives_1_0.eContents().get(0);
		private final Keyword cFieldTypeSEARCHFIELDKeyword_1_0_1 = (Keyword)cFieldTypeAlternatives_1_0.eContents().get(1);
		private final Assignment cIdentifierAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdentifierELEMENTIDENTIFIERParserRuleCall_2_0 = (RuleCall)cIdentifierAssignment_2.eContents().get(0);
		private final Keyword cWithKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cAlternatives_4.eContents().get(0);
		private final Keyword cSavedKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cVarAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cVarVARTYPETerminalRuleCall_4_0_1_0 = (RuleCall)cVarAssignment_4_0_1.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cAlternatives_4.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		
		//FILL:
		//	name='fill' fieldType=('TEXTFIELD' | 'SEARCHFIELD') identifier=ELEMENTIDENTIFIER? 'with' ('saved' var=VARTYPE |
		//	value=STRING);
		@Override public ParserRule getRule() { return rule; }
		
		//name='fill' fieldType=('TEXTFIELD' | 'SEARCHFIELD') identifier=ELEMENTIDENTIFIER? 'with' ('saved' var=VARTYPE |
		//value=STRING)
		public Group getGroup() { return cGroup; }
		
		//name='fill'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'fill'
		public Keyword getNameFillKeyword_0_0() { return cNameFillKeyword_0_0; }
		
		//fieldType=('TEXTFIELD' | 'SEARCHFIELD')
		public Assignment getFieldTypeAssignment_1() { return cFieldTypeAssignment_1; }
		
		//('TEXTFIELD' | 'SEARCHFIELD')
		public Alternatives getFieldTypeAlternatives_1_0() { return cFieldTypeAlternatives_1_0; }
		
		//'TEXTFIELD'
		public Keyword getFieldTypeTEXTFIELDKeyword_1_0_0() { return cFieldTypeTEXTFIELDKeyword_1_0_0; }
		
		//'SEARCHFIELD'
		public Keyword getFieldTypeSEARCHFIELDKeyword_1_0_1() { return cFieldTypeSEARCHFIELDKeyword_1_0_1; }
		
		//identifier=ELEMENTIDENTIFIER?
		public Assignment getIdentifierAssignment_2() { return cIdentifierAssignment_2; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getIdentifierELEMENTIDENTIFIERParserRuleCall_2_0() { return cIdentifierELEMENTIDENTIFIERParserRuleCall_2_0; }
		
		//'with'
		public Keyword getWithKeyword_3() { return cWithKeyword_3; }
		
		//'saved' var=VARTYPE | value=STRING
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//'saved' var=VARTYPE
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//'saved'
		public Keyword getSavedKeyword_4_0_0() { return cSavedKeyword_4_0_0; }
		
		//var=VARTYPE
		public Assignment getVarAssignment_4_0_1() { return cVarAssignment_4_0_1; }
		
		//VARTYPE
		public RuleCall getVarVARTYPETerminalRuleCall_4_0_1_0() { return cVarVARTYPETerminalRuleCall_4_0_1_0; }
		
		//value=STRING
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_4_1_0() { return cValueSTRINGTerminalRuleCall_4_1_0; }
	}
	public class CHECKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.CHECK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameCheckKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Assignment cAllAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cAllAllKeyword_1_0 = (Keyword)cAllAssignment_1.eContents().get(0);
		private final Keyword cCHECKBOXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIdentifierAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIdentifierELEMENTIDENTIFIERParserRuleCall_3_0 = (RuleCall)cIdentifierAssignment_3.eContents().get(0);
		
		//CHECK:
		//	name='check' all='all'? 'CHECKBOX' identifier=ELEMENTIDENTIFIER;
		@Override public ParserRule getRule() { return rule; }
		
		//name='check' all='all'? 'CHECKBOX' identifier=ELEMENTIDENTIFIER
		public Group getGroup() { return cGroup; }
		
		//name='check'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'check'
		public Keyword getNameCheckKeyword_0_0() { return cNameCheckKeyword_0_0; }
		
		//all='all'?
		public Assignment getAllAssignment_1() { return cAllAssignment_1; }
		
		//'all'
		public Keyword getAllAllKeyword_1_0() { return cAllAllKeyword_1_0; }
		
		//'CHECKBOX'
		public Keyword getCHECKBOXKeyword_2() { return cCHECKBOXKeyword_2; }
		
		//identifier=ELEMENTIDENTIFIER
		public Assignment getIdentifierAssignment_3() { return cIdentifierAssignment_3; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getIdentifierELEMENTIDENTIFIERParserRuleCall_3_0() { return cIdentifierELEMENTIDENTIFIERParserRuleCall_3_0; }
	}
	public class UNCHECKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.UNCHECK");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameUncheckKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Assignment cAllAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cAllAllKeyword_1_0 = (Keyword)cAllAssignment_1.eContents().get(0);
		private final Keyword cCHECKBOXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIdentifierAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIdentifierELEMENTIDENTIFIERParserRuleCall_3_0 = (RuleCall)cIdentifierAssignment_3.eContents().get(0);
		
		//UNCHECK:
		//	name='uncheck' all='all'? 'CHECKBOX' identifier=ELEMENTIDENTIFIER;
		@Override public ParserRule getRule() { return rule; }
		
		//name='uncheck' all='all'? 'CHECKBOX' identifier=ELEMENTIDENTIFIER
		public Group getGroup() { return cGroup; }
		
		//name='uncheck'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'uncheck'
		public Keyword getNameUncheckKeyword_0_0() { return cNameUncheckKeyword_0_0; }
		
		//all='all'?
		public Assignment getAllAssignment_1() { return cAllAssignment_1; }
		
		//'all'
		public Keyword getAllAllKeyword_1_0() { return cAllAllKeyword_1_0; }
		
		//'CHECKBOX'
		public Keyword getCHECKBOXKeyword_2() { return cCHECKBOXKeyword_2; }
		
		//identifier=ELEMENTIDENTIFIER
		public Assignment getIdentifierAssignment_3() { return cIdentifierAssignment_3; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getIdentifierELEMENTIDENTIFIERParserRuleCall_3_0() { return cIdentifierELEMENTIDENTIFIERParserRuleCall_3_0; }
	}
	public class SELECTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.SELECT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameSelectKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Assignment cElemAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElemSTRINGTerminalRuleCall_1_0 = (RuleCall)cElemAssignment_1.eContents().get(0);
		private final Keyword cInKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCOMBOBOXKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cIdentifierAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIdentifierELEMENTIDENTIFIERParserRuleCall_4_0 = (RuleCall)cIdentifierAssignment_4.eContents().get(0);
		
		//SELECT:
		//	name='select' elem=STRING 'in' 'COMBOBOX' identifier=ELEMENTIDENTIFIER;
		@Override public ParserRule getRule() { return rule; }
		
		//name='select' elem=STRING 'in' 'COMBOBOX' identifier=ELEMENTIDENTIFIER
		public Group getGroup() { return cGroup; }
		
		//name='select'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'select'
		public Keyword getNameSelectKeyword_0_0() { return cNameSelectKeyword_0_0; }
		
		//elem=STRING
		public Assignment getElemAssignment_1() { return cElemAssignment_1; }
		
		//STRING
		public RuleCall getElemSTRINGTerminalRuleCall_1_0() { return cElemSTRINGTerminalRuleCall_1_0; }
		
		//'in'
		public Keyword getInKeyword_2() { return cInKeyword_2; }
		
		//'COMBOBOX'
		public Keyword getCOMBOBOXKeyword_3() { return cCOMBOBOXKeyword_3; }
		
		//identifier=ELEMENTIDENTIFIER
		public Assignment getIdentifierAssignment_4() { return cIdentifierAssignment_4; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getIdentifierELEMENTIDENTIFIERParserRuleCall_4_0() { return cIdentifierELEMENTIDENTIFIERParserRuleCall_4_0; }
	}
	public class READElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.READ");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameReadKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cUrlKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cBUTTONKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Keyword cLINKKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		private final Keyword cIMAGEKeyword_3_2 = (Keyword)cAlternatives_3.eContents().get(2);
		private final Keyword cTEXTKeyword_3_3 = (Keyword)cAlternatives_3.eContents().get(3);
		private final Assignment cIdentifierAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIdentifierELEMENTIDENTIFIERParserRuleCall_4_0 = (RuleCall)cIdentifierAssignment_4.eContents().get(0);
		private final Assignment cSavePathAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSavePathSAVEVARParserRuleCall_5_0 = (RuleCall)cSavePathAssignment_5.eContents().get(0);
		
		//READ:
		//	name='read' 'url' 'from' ('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER savePath=SAVEVAR?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='read' 'url' 'from' ('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER savePath=SAVEVAR?
		public Group getGroup() { return cGroup; }
		
		//name='read'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'read'
		public Keyword getNameReadKeyword_0_0() { return cNameReadKeyword_0_0; }
		
		//'url'
		public Keyword getUrlKeyword_1() { return cUrlKeyword_1; }
		
		//'from'
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }
		
		//'BUTTON' | 'LINK' | 'IMAGE' | 'TEXT'
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'BUTTON'
		public Keyword getBUTTONKeyword_3_0() { return cBUTTONKeyword_3_0; }
		
		//'LINK'
		public Keyword getLINKKeyword_3_1() { return cLINKKeyword_3_1; }
		
		//'IMAGE'
		public Keyword getIMAGEKeyword_3_2() { return cIMAGEKeyword_3_2; }
		
		//'TEXT'
		public Keyword getTEXTKeyword_3_3() { return cTEXTKeyword_3_3; }
		
		//identifier=ELEMENTIDENTIFIER
		public Assignment getIdentifierAssignment_4() { return cIdentifierAssignment_4; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getIdentifierELEMENTIDENTIFIERParserRuleCall_4_0() { return cIdentifierELEMENTIDENTIFIERParserRuleCall_4_0; }
		
		//savePath=SAVEVAR?
		public Assignment getSavePathAssignment_5() { return cSavePathAssignment_5; }
		
		//SAVEVAR
		public RuleCall getSavePathSAVEVARParserRuleCall_5_0() { return cSavePathSAVEVARParserRuleCall_5_0; }
	}
	public class ELEMENTIDENTIFIERElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.ELEMENTIDENTIFIER");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameIdentifiedKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cByKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cTypeAlternatives_2_0 = (Alternatives)cTypeAssignment_2.eContents().get(0);
		private final Keyword cTypeLABELKeyword_2_0_0 = (Keyword)cTypeAlternatives_2_0.eContents().get(0);
		private final Keyword cTypeCLASSKeyword_2_0_1 = (Keyword)cTypeAlternatives_2_0.eContents().get(1);
		private final Keyword cTypeIDKeyword_2_0_2 = (Keyword)cTypeAlternatives_2_0.eContents().get(2);
		private final Keyword cTypeALTKeyword_2_0_3 = (Keyword)cTypeAlternatives_2_0.eContents().get(3);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cValueSTRINGTerminalRuleCall_3_0_0 = (RuleCall)cValueAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Assignment cInfoAssignment_3_1_0 = (Assignment)cGroup_3_1.eContents().get(0);
		private final Keyword cInfoGivenKeyword_3_1_0_0 = (Keyword)cInfoAssignment_3_1_0.eContents().get(0);
		private final Assignment cVarAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cVarVARTYPETerminalRuleCall_3_1_1_0 = (RuleCall)cVarAssignment_3_1_1.eContents().get(0);
		
		//ELEMENTIDENTIFIER:
		//	name='identified' 'by' type=('LABEL' | 'CLASS' | 'ID' | 'ALT') (value=STRING | info='given' var=VARTYPE);
		@Override public ParserRule getRule() { return rule; }
		
		//name='identified' 'by' type=('LABEL' | 'CLASS' | 'ID' | 'ALT') (value=STRING | info='given' var=VARTYPE)
		public Group getGroup() { return cGroup; }
		
		//name='identified'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'identified'
		public Keyword getNameIdentifiedKeyword_0_0() { return cNameIdentifiedKeyword_0_0; }
		
		//'by'
		public Keyword getByKeyword_1() { return cByKeyword_1; }
		
		//type=('LABEL' | 'CLASS' | 'ID' | 'ALT')
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//('LABEL' | 'CLASS' | 'ID' | 'ALT')
		public Alternatives getTypeAlternatives_2_0() { return cTypeAlternatives_2_0; }
		
		//'LABEL'
		public Keyword getTypeLABELKeyword_2_0_0() { return cTypeLABELKeyword_2_0_0; }
		
		//'CLASS'
		public Keyword getTypeCLASSKeyword_2_0_1() { return cTypeCLASSKeyword_2_0_1; }
		
		//'ID'
		public Keyword getTypeIDKeyword_2_0_2() { return cTypeIDKeyword_2_0_2; }
		
		//'ALT'
		public Keyword getTypeALTKeyword_2_0_3() { return cTypeALTKeyword_2_0_3; }
		
		//value=STRING | info='given' var=VARTYPE
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//value=STRING
		public Assignment getValueAssignment_3_0() { return cValueAssignment_3_0; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_3_0_0() { return cValueSTRINGTerminalRuleCall_3_0_0; }
		
		//info='given' var=VARTYPE
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//info='given'
		public Assignment getInfoAssignment_3_1_0() { return cInfoAssignment_3_1_0; }
		
		//'given'
		public Keyword getInfoGivenKeyword_3_1_0_0() { return cInfoGivenKeyword_3_1_0_0; }
		
		//var=VARTYPE
		public Assignment getVarAssignment_3_1_1() { return cVarAssignment_3_1_1; }
		
		//VARTYPE
		public RuleCall getVarVARTYPETerminalRuleCall_3_1_1_0() { return cVarVARTYPETerminalRuleCall_3_1_1_0; }
	}
	public class VERIFYElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.VERIFY");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVERIFY_CONTAINSParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVERIFY_EQUALSParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//VERIFY:
		//	VERIFY_CONTAINS | VERIFY_EQUALS;
		@Override public ParserRule getRule() { return rule; }
		
		//VERIFY_CONTAINS | VERIFY_EQUALS
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//VERIFY_CONTAINS
		public RuleCall getVERIFY_CONTAINSParserRuleCall_0() { return cVERIFY_CONTAINSParserRuleCall_0; }
		
		//VERIFY_EQUALS
		public RuleCall getVERIFY_EQUALSParserRuleCall_1() { return cVERIFY_EQUALSParserRuleCall_1; }
	}
	public class VERIFY_CONTAINSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.VERIFY_CONTAINS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVerifyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cThatKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cTypeAlternatives_2_0 = (Alternatives)cTypeAssignment_2.eContents().get(0);
		private final Keyword cTypePAGEKeyword_2_0_0 = (Keyword)cTypeAlternatives_2_0.eContents().get(0);
		private final Keyword cTypeTEXTKeyword_2_0_1 = (Keyword)cTypeAlternatives_2_0.eContents().get(1);
		private final Assignment cIdentifierAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIdentifierELEMENTIDENTIFIERParserRuleCall_3_0 = (RuleCall)cIdentifierAssignment_3.eContents().get(0);
		private final Keyword cContainsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Group cGroup_5_0 = (Group)cAlternatives_5.eContents().get(0);
		private final Alternatives cAlternatives_5_0_0 = (Alternatives)cGroup_5_0.eContents().get(0);
		private final Keyword cLINKKeyword_5_0_0_0 = (Keyword)cAlternatives_5_0_0.eContents().get(0);
		private final Keyword cIMAGEKeyword_5_0_0_1 = (Keyword)cAlternatives_5_0_0.eContents().get(1);
		private final Assignment cContainedIdentifierAssignment_5_0_1 = (Assignment)cGroup_5_0.eContents().get(1);
		private final RuleCall cContainedIdentifierELEMENTIDENTIFIERParserRuleCall_5_0_1_0 = (RuleCall)cContainedIdentifierAssignment_5_0_1.eContents().get(0);
		private final Alternatives cAlternatives_5_1 = (Alternatives)cAlternatives_5.eContents().get(1);
		private final Assignment cValueAssignment_5_1_0 = (Assignment)cAlternatives_5_1.eContents().get(0);
		private final RuleCall cValueSTRINGTerminalRuleCall_5_1_0_0 = (RuleCall)cValueAssignment_5_1_0.eContents().get(0);
		private final Assignment cVariableAssignment_5_1_1 = (Assignment)cAlternatives_5_1.eContents().get(1);
		private final RuleCall cVariableREGISTERED_VALUEParserRuleCall_5_1_1_0 = (RuleCall)cVariableAssignment_5_1_1.eContents().get(0);
		
		//VERIFY_CONTAINS:
		//	'verify' 'that' type=('PAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER? 'contains' (('LINK' | 'IMAGE')
		//	containedIdentifier=ELEMENTIDENTIFIER | (value=STRING | variable=REGISTERED_VALUE));
		@Override public ParserRule getRule() { return rule; }
		
		//'verify' 'that' type=('PAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER? 'contains' (('LINK' | 'IMAGE')
		//containedIdentifier=ELEMENTIDENTIFIER | (value=STRING | variable=REGISTERED_VALUE))
		public Group getGroup() { return cGroup; }
		
		//'verify'
		public Keyword getVerifyKeyword_0() { return cVerifyKeyword_0; }
		
		//'that'
		public Keyword getThatKeyword_1() { return cThatKeyword_1; }
		
		//type=('PAGE' | 'TEXT')
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//('PAGE' | 'TEXT')
		public Alternatives getTypeAlternatives_2_0() { return cTypeAlternatives_2_0; }
		
		//'PAGE'
		public Keyword getTypePAGEKeyword_2_0_0() { return cTypePAGEKeyword_2_0_0; }
		
		//'TEXT'
		public Keyword getTypeTEXTKeyword_2_0_1() { return cTypeTEXTKeyword_2_0_1; }
		
		//identifier=ELEMENTIDENTIFIER?
		public Assignment getIdentifierAssignment_3() { return cIdentifierAssignment_3; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getIdentifierELEMENTIDENTIFIERParserRuleCall_3_0() { return cIdentifierELEMENTIDENTIFIERParserRuleCall_3_0; }
		
		//'contains'
		public Keyword getContainsKeyword_4() { return cContainsKeyword_4; }
		
		//('LINK' | 'IMAGE') containedIdentifier=ELEMENTIDENTIFIER | (value=STRING | variable=REGISTERED_VALUE)
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//('LINK' | 'IMAGE') containedIdentifier=ELEMENTIDENTIFIER
		public Group getGroup_5_0() { return cGroup_5_0; }
		
		//'LINK' | 'IMAGE'
		public Alternatives getAlternatives_5_0_0() { return cAlternatives_5_0_0; }
		
		//'LINK'
		public Keyword getLINKKeyword_5_0_0_0() { return cLINKKeyword_5_0_0_0; }
		
		//'IMAGE'
		public Keyword getIMAGEKeyword_5_0_0_1() { return cIMAGEKeyword_5_0_0_1; }
		
		//containedIdentifier=ELEMENTIDENTIFIER
		public Assignment getContainedIdentifierAssignment_5_0_1() { return cContainedIdentifierAssignment_5_0_1; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getContainedIdentifierELEMENTIDENTIFIERParserRuleCall_5_0_1_0() { return cContainedIdentifierELEMENTIDENTIFIERParserRuleCall_5_0_1_0; }
		
		//(value=STRING | variable=REGISTERED_VALUE)
		public Alternatives getAlternatives_5_1() { return cAlternatives_5_1; }
		
		//value=STRING
		public Assignment getValueAssignment_5_1_0() { return cValueAssignment_5_1_0; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_5_1_0_0() { return cValueSTRINGTerminalRuleCall_5_1_0_0; }
		
		//variable=REGISTERED_VALUE
		public Assignment getVariableAssignment_5_1_1() { return cVariableAssignment_5_1_1; }
		
		//REGISTERED_VALUE
		public RuleCall getVariableREGISTERED_VALUEParserRuleCall_5_1_1_0() { return cVariableREGISTERED_VALUEParserRuleCall_5_1_1_0; }
	}
	public class VERIFY_EQUALSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.VERIFY_EQUALS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVerifyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cThatKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOperationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOperationCOUNTParserRuleCall_2_0 = (RuleCall)cOperationAssignment_2.eContents().get(0);
		private final Keyword cEqualsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_4_0 = (Assignment)cAlternatives_4.eContents().get(0);
		private final RuleCall cValueSTRINGTerminalRuleCall_4_0_0 = (RuleCall)cValueAssignment_4_0.eContents().get(0);
		private final Assignment cRegisteredValueAssignment_4_1 = (Assignment)cAlternatives_4.eContents().get(1);
		private final RuleCall cRegisteredValueREGISTERED_VALUEParserRuleCall_4_1_0 = (RuleCall)cRegisteredValueAssignment_4_1.eContents().get(0);
		
		//VERIFY_EQUALS:
		//	'verify' 'that' operation=COUNT 'equals' (value=STRING | registeredValue=REGISTERED_VALUE);
		@Override public ParserRule getRule() { return rule; }
		
		//'verify' 'that' operation=COUNT 'equals' (value=STRING | registeredValue=REGISTERED_VALUE)
		public Group getGroup() { return cGroup; }
		
		//'verify'
		public Keyword getVerifyKeyword_0() { return cVerifyKeyword_0; }
		
		//'that'
		public Keyword getThatKeyword_1() { return cThatKeyword_1; }
		
		//operation=COUNT
		public Assignment getOperationAssignment_2() { return cOperationAssignment_2; }
		
		//COUNT
		public RuleCall getOperationCOUNTParserRuleCall_2_0() { return cOperationCOUNTParserRuleCall_2_0; }
		
		//'equals'
		public Keyword getEqualsKeyword_3() { return cEqualsKeyword_3; }
		
		//value=STRING | registeredValue=REGISTERED_VALUE
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//value=STRING
		public Assignment getValueAssignment_4_0() { return cValueAssignment_4_0; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_4_0_0() { return cValueSTRINGTerminalRuleCall_4_0_0; }
		
		//registeredValue=REGISTERED_VALUE
		public Assignment getRegisteredValueAssignment_4_1() { return cRegisteredValueAssignment_4_1; }
		
		//REGISTERED_VALUE
		public RuleCall getRegisteredValueREGISTERED_VALUEParserRuleCall_4_1_0() { return cRegisteredValueREGISTERED_VALUEParserRuleCall_4_1_0; }
	}
	public class REGISTERED_VALUEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.REGISTERED_VALUE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSavedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarVARTYPETerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//REGISTERED_VALUE:
		//	'saved' var=VARTYPE;
		@Override public ParserRule getRule() { return rule; }
		
		//'saved' var=VARTYPE
		public Group getGroup() { return cGroup; }
		
		//'saved'
		public Keyword getSavedKeyword_0() { return cSavedKeyword_0; }
		
		//var=VARTYPE
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//VARTYPE
		public RuleCall getVarVARTYPETerminalRuleCall_1_0() { return cVarVARTYPETerminalRuleCall_1_0; }
	}
	public class COUNTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.COUNT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameCountKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cELEMENTKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdentifierAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdentifierELEMENTIDENTIFIERParserRuleCall_2_0 = (RuleCall)cIdentifierAssignment_2.eContents().get(0);
		private final Assignment cSaveVariableAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSaveVariableSAVEVARParserRuleCall_3_0 = (RuleCall)cSaveVariableAssignment_3.eContents().get(0);
		
		//COUNT:
		//	name='count' 'ELEMENT' identifier=ELEMENTIDENTIFIER saveVariable=SAVEVAR?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='count' 'ELEMENT' identifier=ELEMENTIDENTIFIER saveVariable=SAVEVAR?
		public Group getGroup() { return cGroup; }
		
		//name='count'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'count'
		public Keyword getNameCountKeyword_0_0() { return cNameCountKeyword_0_0; }
		
		//'ELEMENT'
		public Keyword getELEMENTKeyword_1() { return cELEMENTKeyword_1; }
		
		//identifier=ELEMENTIDENTIFIER
		public Assignment getIdentifierAssignment_2() { return cIdentifierAssignment_2; }
		
		//ELEMENTIDENTIFIER
		public RuleCall getIdentifierELEMENTIDENTIFIERParserRuleCall_2_0() { return cIdentifierELEMENTIDENTIFIERParserRuleCall_2_0; }
		
		//saveVariable=SAVEVAR?
		public Assignment getSaveVariableAssignment_3() { return cSaveVariableAssignment_3; }
		
		//SAVEVAR
		public RuleCall getSaveVariableSAVEVARParserRuleCall_3_0() { return cSaveVariableSAVEVARParserRuleCall_3_0; }
	}
	public class SAVEVARElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.SAVEVAR");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAndKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cSaveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cInKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cVarAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVarVARTYPETerminalRuleCall_3_0 = (RuleCall)cVarAssignment_3.eContents().get(0);
		
		//SAVEVAR:
		//	'and' 'save' 'in' var=VARTYPE;
		@Override public ParserRule getRule() { return rule; }
		
		//'and' 'save' 'in' var=VARTYPE
		public Group getGroup() { return cGroup; }
		
		//'and'
		public Keyword getAndKeyword_0() { return cAndKeyword_0; }
		
		//'save'
		public Keyword getSaveKeyword_1() { return cSaveKeyword_1; }
		
		//'in'
		public Keyword getInKeyword_2() { return cInKeyword_2; }
		
		//var=VARTYPE
		public Assignment getVarAssignment_3() { return cVarAssignment_3; }
		
		//VARTYPE
		public RuleCall getVarVARTYPETerminalRuleCall_3_0() { return cVarVARTYPETerminalRuleCall_3_0; }
	}
	public class PLAYElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.PLAY");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNamePlayKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cProcedureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPreocedureAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPreocedureVARTYPETerminalRuleCall_2_0 = (RuleCall)cPreocedureAssignment_2.eContents().get(0);
		private final Assignment cParamsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParamsSTRINGTerminalRuleCall_3_0 = (RuleCall)cParamsAssignment_3.eContents().get(0);
		
		//PLAY:
		//	name='play' 'procedure' preocedure=VARTYPE params+=STRING*;
		@Override public ParserRule getRule() { return rule; }
		
		//name='play' 'procedure' preocedure=VARTYPE params+=STRING*
		public Group getGroup() { return cGroup; }
		
		//name='play'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'play'
		public Keyword getNamePlayKeyword_0_0() { return cNamePlayKeyword_0_0; }
		
		//'procedure'
		public Keyword getProcedureKeyword_1() { return cProcedureKeyword_1; }
		
		//preocedure=VARTYPE
		public Assignment getPreocedureAssignment_2() { return cPreocedureAssignment_2; }
		
		//VARTYPE
		public RuleCall getPreocedureVARTYPETerminalRuleCall_2_0() { return cPreocedureVARTYPETerminalRuleCall_2_0; }
		
		//params+=STRING*
		public Assignment getParamsAssignment_3() { return cParamsAssignment_3; }
		
		//STRING
		public RuleCall getParamsSTRINGTerminalRuleCall_3_0() { return cParamsSTRINGTerminalRuleCall_3_0; }
	}
	
	
	private final PROGRAMMEElements pPROGRAMME;
	private final PROCEDUREElements pPROCEDURE;
	private final INSTRUCTIONElements pINSTRUCTION;
	private final OPENElements pOPEN;
	private final GOTOElements pGOTO;
	private final CLICKElements pCLICK;
	private final FILLElements pFILL;
	private final CHECKElements pCHECK;
	private final UNCHECKElements pUNCHECK;
	private final SELECTElements pSELECT;
	private final READElements pREAD;
	private final ELEMENTIDENTIFIERElements pELEMENTIDENTIFIER;
	private final VERIFYElements pVERIFY;
	private final VERIFY_CONTAINSElements pVERIFY_CONTAINS;
	private final VERIFY_EQUALSElements pVERIFY_EQUALS;
	private final REGISTERED_VALUEElements pREGISTERED_VALUE;
	private final COUNTElements pCOUNT;
	private final SAVEVARElements pSAVEVAR;
	private final PLAYElements pPLAY;
	private final TerminalRule tVARTYPE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DomainmodelGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPROGRAMME = new PROGRAMMEElements();
		this.pPROCEDURE = new PROCEDUREElements();
		this.pINSTRUCTION = new INSTRUCTIONElements();
		this.pOPEN = new OPENElements();
		this.pGOTO = new GOTOElements();
		this.pCLICK = new CLICKElements();
		this.pFILL = new FILLElements();
		this.pCHECK = new CHECKElements();
		this.pUNCHECK = new UNCHECKElements();
		this.pSELECT = new SELECTElements();
		this.pREAD = new READElements();
		this.pELEMENTIDENTIFIER = new ELEMENTIDENTIFIERElements();
		this.pVERIFY = new VERIFYElements();
		this.pVERIFY_CONTAINS = new VERIFY_CONTAINSElements();
		this.pVERIFY_EQUALS = new VERIFY_EQUALSElements();
		this.pREGISTERED_VALUE = new REGISTERED_VALUEElements();
		this.pCOUNT = new COUNTElements();
		this.pSAVEVAR = new SAVEVARElements();
		this.pPLAY = new PLAYElements();
		this.tVARTYPE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.project.browserautomationdsl.Domainmodel.VARTYPE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.project.browserautomationdsl.Domainmodel".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//PROGRAMME:
	//	procedures+=PROCEDURE*;
	public PROGRAMMEElements getPROGRAMMEAccess() {
		return pPROGRAMME;
	}
	
	public ParserRule getPROGRAMMERule() {
		return getPROGRAMMEAccess().getRule();
	}
	
	//PROCEDURE:
	//	'procedure' name=VARTYPE ('with' param=VARTYPE params+=VARTYPE*)?
	//	inst+=INSTRUCTION*;
	public PROCEDUREElements getPROCEDUREAccess() {
		return pPROCEDURE;
	}
	
	public ParserRule getPROCEDURERule() {
		return getPROCEDUREAccess().getRule();
	}
	
	//INSTRUCTION:
	//	OPEN
	//	| CLICK
	//	| CHECK
	//	| UNCHECK
	//	| READ
	//	| COUNT
	//	| VERIFY
	//	| SELECT
	//	| GOTO
	//	| FILL
	//	| PLAY;
	public INSTRUCTIONElements getINSTRUCTIONAccess() {
		return pINSTRUCTION;
	}
	
	public ParserRule getINSTRUCTIONRule() {
		return getINSTRUCTIONAccess().getRule();
	}
	
	//OPEN:
	//	name='open' value=('FIREFOX' | 'CHROME');
	public OPENElements getOPENAccess() {
		return pOPEN;
	}
	
	public ParserRule getOPENRule() {
		return getOPENAccess().getRule();
	}
	
	//GOTO:
	//	name='go to' 'given'? value=STRING;
	public GOTOElements getGOTOAccess() {
		return pGOTO;
	}
	
	public ParserRule getGOTORule() {
		return getGOTOAccess().getRule();
	}
	
	//CLICK:
	//	name='click' 'on' type=('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER;
	public CLICKElements getCLICKAccess() {
		return pCLICK;
	}
	
	public ParserRule getCLICKRule() {
		return getCLICKAccess().getRule();
	}
	
	//FILL:
	//	name='fill' fieldType=('TEXTFIELD' | 'SEARCHFIELD') identifier=ELEMENTIDENTIFIER? 'with' ('saved' var=VARTYPE |
	//	value=STRING);
	public FILLElements getFILLAccess() {
		return pFILL;
	}
	
	public ParserRule getFILLRule() {
		return getFILLAccess().getRule();
	}
	
	//CHECK:
	//	name='check' all='all'? 'CHECKBOX' identifier=ELEMENTIDENTIFIER;
	public CHECKElements getCHECKAccess() {
		return pCHECK;
	}
	
	public ParserRule getCHECKRule() {
		return getCHECKAccess().getRule();
	}
	
	//UNCHECK:
	//	name='uncheck' all='all'? 'CHECKBOX' identifier=ELEMENTIDENTIFIER;
	public UNCHECKElements getUNCHECKAccess() {
		return pUNCHECK;
	}
	
	public ParserRule getUNCHECKRule() {
		return getUNCHECKAccess().getRule();
	}
	
	//SELECT:
	//	name='select' elem=STRING 'in' 'COMBOBOX' identifier=ELEMENTIDENTIFIER;
	public SELECTElements getSELECTAccess() {
		return pSELECT;
	}
	
	public ParserRule getSELECTRule() {
		return getSELECTAccess().getRule();
	}
	
	//READ:
	//	name='read' 'url' 'from' ('BUTTON' | 'LINK' | 'IMAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER savePath=SAVEVAR?;
	public READElements getREADAccess() {
		return pREAD;
	}
	
	public ParserRule getREADRule() {
		return getREADAccess().getRule();
	}
	
	//ELEMENTIDENTIFIER:
	//	name='identified' 'by' type=('LABEL' | 'CLASS' | 'ID' | 'ALT') (value=STRING | info='given' var=VARTYPE);
	public ELEMENTIDENTIFIERElements getELEMENTIDENTIFIERAccess() {
		return pELEMENTIDENTIFIER;
	}
	
	public ParserRule getELEMENTIDENTIFIERRule() {
		return getELEMENTIDENTIFIERAccess().getRule();
	}
	
	//VERIFY:
	//	VERIFY_CONTAINS | VERIFY_EQUALS;
	public VERIFYElements getVERIFYAccess() {
		return pVERIFY;
	}
	
	public ParserRule getVERIFYRule() {
		return getVERIFYAccess().getRule();
	}
	
	//VERIFY_CONTAINS:
	//	'verify' 'that' type=('PAGE' | 'TEXT') identifier=ELEMENTIDENTIFIER? 'contains' (('LINK' | 'IMAGE')
	//	containedIdentifier=ELEMENTIDENTIFIER | (value=STRING | variable=REGISTERED_VALUE));
	public VERIFY_CONTAINSElements getVERIFY_CONTAINSAccess() {
		return pVERIFY_CONTAINS;
	}
	
	public ParserRule getVERIFY_CONTAINSRule() {
		return getVERIFY_CONTAINSAccess().getRule();
	}
	
	//VERIFY_EQUALS:
	//	'verify' 'that' operation=COUNT 'equals' (value=STRING | registeredValue=REGISTERED_VALUE);
	public VERIFY_EQUALSElements getVERIFY_EQUALSAccess() {
		return pVERIFY_EQUALS;
	}
	
	public ParserRule getVERIFY_EQUALSRule() {
		return getVERIFY_EQUALSAccess().getRule();
	}
	
	//REGISTERED_VALUE:
	//	'saved' var=VARTYPE;
	public REGISTERED_VALUEElements getREGISTERED_VALUEAccess() {
		return pREGISTERED_VALUE;
	}
	
	public ParserRule getREGISTERED_VALUERule() {
		return getREGISTERED_VALUEAccess().getRule();
	}
	
	//COUNT:
	//	name='count' 'ELEMENT' identifier=ELEMENTIDENTIFIER saveVariable=SAVEVAR?;
	public COUNTElements getCOUNTAccess() {
		return pCOUNT;
	}
	
	public ParserRule getCOUNTRule() {
		return getCOUNTAccess().getRule();
	}
	
	//SAVEVAR:
	//	'and' 'save' 'in' var=VARTYPE;
	public SAVEVARElements getSAVEVARAccess() {
		return pSAVEVAR;
	}
	
	public ParserRule getSAVEVARRule() {
		return getSAVEVARAccess().getRule();
	}
	
	//PLAY:
	//	name='play' 'procedure' preocedure=VARTYPE params+=STRING*;
	public PLAYElements getPLAYAccess() {
		return pPLAY;
	}
	
	public ParserRule getPLAYRule() {
		return getPLAYAccess().getRule();
	}
	
	//terminal VARTYPE:
	//	'A'..'Z' | 'a'..'z' | INT | '_' | '-'*;
	public TerminalRule getVARTYPERule() {
		return tVARTYPE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
